### ISSUE TITLE
Initialise Phoenix application

### ISSUE THREAD

**Issue by SimonLab** [dwyl/auth-mvp#1]
linked to https://github.com/dwyl/auth/issues/40#issuecomment-585297245

+ [x] Create a new Phoenix application with `mix phx.new auth-mvp --app auth_mvp` . We might need to render some html from the auth application so I'm not adding the `--no-webpack` and `--no-html` option

+ [x] Use [elixir-auth-google](https://github.com/dwyl/elixir-auth-google/) and [elixir-auth-github](https://github.com/dwyl/elixir-auth-google/)
  - [x] Add the packages as dependencies
  - [x] Create `/auth/urls` endpoint using the `api` scope and returns the list of the oauth urls
  - [x] Create callback endpoints. These endpoints are were the Google and Github application will send the token once the user authenticate. `/auth/google/callback` and `/auth/github/callback

+ [x] Allow [Cross Origin Resource Sharing](https://developer.mozilla.org/en-US/docs/Web/HTTP/CORS) to allow requests to access the auth api endpoints
  - [x] Add the [cors_plug](https://github.com/mschae/cors_plug) dependency
  - [x] Update the `endpoint.ex` file to add the line `plug CORSPlug, origin: ["*"]`

+ [x] Deploy the application on Heroku
  - [x] Define the callback url to match the heroku name of the application. This allow the `/api/auth/github/callback` (and the google one) to be available for the Oauth apps
  - [x] Generate a new secret key and add it to the environment variables on Heroku, `mix phx.gen.secret`
  - [x] Add Postgres resource on Heroku
  - [x] Follow the heroku deployment guide to make sure the application is ready: https://hexdocs.pm/phoenix/heroku.html

**Comment by SimonLab** [comment]
elixir_auth_google has just been updated: https://github.com/dwyl/elixir-auth-google/pull/34#issuecomment-587076290

Updating the dependency and the code now

**Comment by SimonLab** [comment]
Focusing now on adding tests for the 3 endpoints:
https://github.com/dwyl/auth-mvp/blob/72d883cbb74cef428be14d570885b09119554fb6/lib/auth_mvp_web/router.ex#L23-L29

The packages `elixir_auth_google` and `elixir_auth_github` are sending request to the Oauth apps, however as these packages are already tested and the tests for auth should focus on the logic of the controller, I'm thinking to mock the functions linked to these two packages.

see http://blog.plataformatec.com.br/2015/10/mocks-and-explicit-contracts/

**Comment by nelsonic** [comment]
This is done. 👍
