### ISSUE TITLE
Create jwt with Joken

### ISSUE THREAD

**Issue by SimonLab** [dwyl/auth-mvp#3]
Currently the jwt created on the callback url for Google or Github is hardcoded:
https://github.com/dwyl/auth-mvp/blob/1232eafeba21ff993bc7b4e9feae7b78d4e8f4d1/lib/auth_mvp_web/controllers/google_auth_controller.ex#L13

+ [x] Use [Joken](https://github.com/joken-elixir/joken)  to create a "real" jwt that will be send back to the client

**Comment by SimonLab** [comment]
Using `generate_and_sign!` function with the `%{email: ...} added claim.
We can get back the claim from a jwt with `verify_and_validate!`


![image](https://user-images.githubusercontent.com/6057298/74740659-9dbafb80-525b-11ea-9c15-74f7f1a43c5e.png)

**Comment by nelsonic** [comment]
PR #11 merged. ✅
